[build-system]
requires = [
  "pip>=10.0",
  "setuptools>=42",
  "wheel",
  "pybind11>=2.9.0",
  "scikit-build",
  "cmake",
  "ninja; platform_system!='Windows'",
]

build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"
