[build-system]
requires = [
  "pip>=22.0.4",
  "setuptools>=42",
  "wheel",
  "pybind11",
  "requests",
  "setuptools_scm",
  "scikit-build",
]

build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"
