name: rlassopy_env
channels:
- conda-forge
- defaults
dependencies:
  # readthedocs requirements
  - python=3.8
  - pip>=20.1
  - pybind11
  - scikit-build
  # rlassopy requirements
  - numpy
  - scipy
  - scikit-learn
  - patsy
  - pandas
