name: docs_pages_workflow
 
# execute this workflow automatically when a we push to master
on:
  push:
    branches: [ master ]
 
jobs:
 
  build_docs_job:
    runs-on: ubuntu-latest
    container: "ubuntu:devel"

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    # container: debian:buster-slim
 
    steps:

    # - name: setup conda 
    #   uses: conda-incubator/setup-miniconda@v2
    #   with:
    #     miniconda-version: "latest"
    #     activate-environment: docs_env
    #       #environment-file: docs/environment.yml
    #     python-version: 3.7
    #     auto-activate-base: false
    # - name: setup python-version
    #   uses: actions/setup-python@v3
    #   with: 
    #     python-version: "3.8"
    #
    # - name: Install doc dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r docs/requirements.txt
    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Set up Python
      uses: actions/setup-python@v2.2.1
      with:
        python-version: 3.9

    - name: Install Pandoc system copy
      run: |
        sudo apt update
        sudo apt install pandoc

    - name: Install doc dependencies
      run: | 
        python -m pip install --upgrade pip 
        python -m pip install -U sphinx
        python -m pip install sphinx-gallery sphinx_rtd_theme numpydoc pandoc ipython nbsphinx markupsafe

    - name: Install RlassoModels
      run: | 
        python -m pip install .

    
    
    - name: make the sphinx docs
      run: |
        make -C docs clean
        make -C docs html

              
    - name: Init new repo in dist folder and commit
      run: |
        cd docs/build/html/
        git init
        touch .nojekyll
        git add -A
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m 'deploy'

    - name: work around permission issue
      run: git config --global --add safe.directory /github/workspace/docs/build/html

    - name: Trust My Directory
      run: |
          apt-get install -y git
          export GIT_CEILING_DIRECTORIES=/__w # don't work

    - name: Force push to destination branch
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        force: true
        directory: ./docs/build/html

 #    - name: Prereqs
 #      env:
 #        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 #      run: |
 #        apt-get update
 #        apt-get install -y git
 #        git clone --depth 1 "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" .
 #      shell: bash
 # 
 #    - name: Make executable
 #      env:
 #        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 #      run: chmod +x docs/buildDocs.sh
 #      shell: bash
 #
 #    - name: Execute script to build our documentation and update pages
 #      env:
 #        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 #      run: docs/buildDocs.sh
 #      shell: bash
